services:
  - type: web
    name: chatapp
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne chatproject.asgi:application --port $PORT --bind 0.0.0.0"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: REDIS_URL
        fromService:
          name: chat-redis
          type: redis
          property: connectionString

  - type: redis
    name: chat-redis
    plan: free
